services:
- type: web
  name: steel-defect-app
  env: python
  buildCommand: "pip install -r requirements.txt"
  startCommand: "bash setup.sh && streamlit run app.py"
  branch: main
  plan: free
  autoDeploy: true